"""Alembic environment for the app_meta database.

Migrations here are hand-written SQL rather than autogenerated from models: the
schema leans on Postgres features (generated columns, trigram indexes, column
comments) that read more clearly as SQL, and neither service needs ORM models
of these tables. That's why there is no target_metadata below.
"""

import asyncio
import os
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from dotenv import load_dotenv
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import create_async_engine

# Pick up the repo-level .env for local development. Variables already set in the
# real environment (CI, containers) take precedence.
load_dotenv(Path(__file__).resolve().parents[2] / ".env")

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)


def _database_url() -> str:
    url = os.environ.get("APP_META_MIGRATIONS_URL")
    if not url:
        raise RuntimeError(
            "APP_META_MIGRATIONS_URL is not set. Copy .env.example to .env "
            "(or export the variable) before running migrations."
        )
    return url


def run_migrations_offline() -> None:
    """Emit the SQL to stdout instead of running it (alembic upgrade head --sql)."""
    context.configure(url=_database_url(), literal_binds=True, dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.run_migrations()


def _run_migrations(connection) -> None:
    context.configure(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    engine = create_async_engine(_database_url(), poolclass=pool.NullPool)
    async with engine.connect() as connection:
        await connection.run_sync(_run_migrations)
    await engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
